import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardLayout from "./DashboardLayout";
// import Navbar from "@/components/shared/navbar/Navbar";
// import Footer from "@/components/shared/footer/Footer"; //added DashboardLayout to hide navbar by tushar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Medicare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header>
          <Navbar />
        </header> */}

        {/* <main>{children}</main> */}
        <DashboardLayout>{children}</DashboardLayout>

        {/* <footer className="">
          <Footer />
        </footer> */}
      </body>
    </html>
  );
}
